### ISSUE TITLE
add: bookinproceedings

### ISSUE THREAD

**Issue by ClintEastwood** [maieul/biblatex-bookinarticle#10]
I have now another peculiar new type that seesm to be worthy of inclusion into your package: an edition of an ancient text published in the proceedings of a conference:

    %!TEX TS-program = lualatexmk
    \documentclass{scrartcl}
    \usepackage{fontspec}
    \usepackage[backend=biber,style=authortitle-comp,abbreviate=false]{biblatex}
    \usepackage{biblatex-bookinarticle}
    \usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @proceedings{doe:proceedings:2012,
    	Editor = {John Doe},
    	Eventdate = {2010-01-01/2010-01-05},
    	Location = {Paris},
    	Publisher = {Publisher},
    	Series = {Name of a Series},
    	Number = {13},
    	Subtitle = {A Nice Collection of Papers},
    	Title = {A Very Nice Collection},
    	Titleaddon = {Proceedings of a Very Nice Conference},
    	Venue = {Conference Hall at the Sorbonne},
    	Year = {2012}}
    @bookinproceedings{aristotle:doe:proceedings:2012,
    	Author = {Aristotle},
    	Title = {The Ancient Text},
    	Crossref = {doe:proceedings:2012},
    	Pages = {100--155},
    	Titleaddon = {\bibstring{byeditorin} Editor's Name}}
    \end{filecontents}
    \addbibresource{\jobname.bib}
    \begin{document}
    This is the proceedings: \cite{doe:proceedings:2012} and this is the edition published in the proceedings: \cite{aristotle:doe:proceedings:2012}.
    \printbibliography
    \end{document}

Please note: this is not a case of a book**inin**proceedings but of a book**in**proceedings -- so one may also think about a book**in**collection in addition to the book**inin**collection.

Many thanks again!
ClintEastwood

**Comment by maieul** [comment]
shoud be @bookininproceedings, isn't it ? as for @bookinincollection

could look on it this week-end.

**Comment by maieul** [comment]
Dear @ClintEastwood could you precise you need : is it a book edited IN a contribution of  a proceedings (@bookininproceedings) or a book edited AS a contribution of a proceedings (@bookinproceedings) ?

**Comment by ClintEastwood** [comment]
Yes. I was busy today. 
It is indeed (as I stated) a book-in-proceedings and not a book-inin-proceedings. But to be honest, I think we need all combinations:

(book-in-book --> already implemented)
book-in-collection
book-in-proceedings
(book-in-thesis --> already implemented by your package)

(book-in-article --> already implemented by your package)
(book-in-in-collection --> already implemented by your package)
book-in-in-proceedings

**Comment by maieul** [comment]
you're right.
book-in-collection and book-in-proceedings should be easy to implement

**Comment by ClintEastwood** [comment]
but book-in-in-proceedings is almost the same as book-in-in-collection which you already implemented. So that should not be too difficult either, or am I mistaken?

**Comment by maieul** [comment]
as the driver for in-collection differs to the driver for in-proceedings in standard.bbx, the in-in* drivers should also differs.

It won't be difficult, but need test (also for crossref mechanism !)

**Comment by ClintEastwood** [comment]
I will test whatever you upload.

**Comment by maieul** [comment]
what do you think about changing name ? because now, it does more than bookinarticle.

maybe bookinsomething ? bookinothertype ?

**Comment by maieul** [comment]
@ClintEastwood please, spoke on #11 about changing name.

**Comment by maieul** [comment]
@ClintEastwood why do you systematicaly add a titleaddon field ? the editor should be normal field. For @bookinarticle and @bookinthesis, it it the author of the thesis/article.

But for @bookinproceedings and @bookinreference, we should add a new field, call "bookeditor", which mean for the editor of the @proceedings or @reference. It will clearly need a break in the code, because requiring to load it is a bbx file, so with the bibstyle option.

**Comment by ClintEastwood** [comment]
I am using the titleaddon-field precisely because it is the easiest way of specifying translator/editor roles and I think it would be good to acknowledge this. Especially since for example I can think of an ancient work being translated by X whose translation is published as an appendix in the article/incollection/etc of Y. In that case, there is currently no way to acknowledge the efforts of X -- or am I mistaken?

**Comment by maieul** [comment]
Ah ! in the case of X ≠ Y, you are right. But I don't think using titleaddon is a good way, because it should for a addon to the title, not other data. For example, it will be incompatible with biblatex-source-division. 

We should create more field for this type of case, and print them as normal field, so with normal system. Using  `\bibstring{byeditorin}` in a field is just a aberration, a field should not included formating command.

So that open many, many new question. We should thing at a coherent and single system of editor / translator / author field for each level. 

I have to think about that before coding any new thing.

**Comment by ClintEastwood** [comment]
See my remark here: https://github.com/maieul/biblatex-bookinarticle/issues/12#issuecomment-187644033

I kind of like my solution with using the `Titleaddon` field in that way. it's perfect (e.g. because the titleaddon of a book is never in italics and so is well fitted for containing this kind of information. And if I remember correctly, `Note` and `Addendum` add the information somewhere else.)

**Comment by maieul** [comment]
You make mistake between forms and meaning (and you don't solve the problem of "where to put the book subdivision, if we use titleaddon for editor"). Each field with its meaning, and many problem are avoided.

**Comment by ClintEastwood** [comment]
Don't misunderstand: I fully encourage you to come up with a solution and I will certainly help and test everything you upload.

**Comment by maieul** [comment]
yes, yes, I know. I just want to take your attention of that shorter solution are not better solution.

**Comment by maieul** [comment]
So, now https://git.framasoft.org/maieul/biblatex-morename has been created. I can start working on this problem.

**Comment by maieul** [comment]
(Personnal notes)
todo list
- book-in-collection
- book-in-proceedings
- <s>book-in-in-proceedings</s>

**Comment by maieul** [comment]
I have created the the new entry type. I have to add the new field. I will open a new issue for testing.
