### ISSUE TITLE
changing name

### ISSUE THREAD

**Issue by maieul** [maieul/biblatex-bookinarticle#11]
@moewew, @sonator, @doc73 @clinsteastwood : what do you think about changing the name of this package, to have a less restricted name ? maybe:
bookinsomething ? bookinothertype ?

it will be also a changing of number, but without breaking compatibility.

**Comment by maieul** [comment]
I said @ClintEastwood

**Comment by Doc73** [comment]
Yes, Good Idea!
I'd suggest... `bookinpublication` or a simpler `bookinother`.

**Comment by ClintEastwood** [comment]
I agree. It's a good idea. Would vote for "bookinother".

**Comment by moewew** [comment]
Allow me to be the spoilsport for a moment.

I tend to be quite conservative when it comes to renaming things. Renaming an entire package might have some unwanted consequences (I don't know how CTAN handles that, would they continue to stock an old version of the old package so it can be found and used in the future: that would effectively mean some kind of branching with one branch become stale instantly; could all requests be redirected to the new package?).

I don't think it is that bad to have a package name that seems a bit more specialised than what is actually provided. I'm not sure if the new name would really make it that much easier for people to find the package. Plus you need to think about people knowing the package under the old name (brand recognition, if you will).

**Comment by maieul** [comment]
@spoilsport ok. I don't know in general. 

But now, I am thinking on #12. And it seems we will need to change the way the package will be loaded. A .sty file could not work anymore, because we need new field, so .dbx / .bbx file, and so loading in with bibstyle=Something. So it could be a good occasion to change the name.

**Comment by moewew** [comment]
Well, if your package changes the way it works dramatically, a name change might not be that bad after all. In fact I'm all for changing the name if you change the package from `.sty` to `.dbx`/`.bbx`, so you may safely discard my reservations from before in that case. Just be sure to still let the old package live on CTAN with a note that its functionality is superseded by the new package.

**Comment by maieul** [comment]
yes, I have already done it in the past for (r)(e)ledmac ;-)

**Comment by moewew** [comment]
Ahh, I should have remembered that. You probably know better what to do than I.

**Comment by ClintEastwood** [comment]
yes, perhaps moewew's concern is right. do what you did with ledmac and create a new one while saying that the old one has been superseded.

about `dbx`, `bbx`, `sty`, I have no clue and cannot advise anything (even though I'd be eager to learn).
