### ISSUE TITLE
Try biblatex-bookinother and biblatex-morenames

### ISSUE THREAD

**Issue by maieul** [maieul/biblatex-bookinarticle#16]
Dear @ClintEastwood and @Doc75, 

I have finished – I hope –  to implement the requirement for #5, #11, #12, #13, #14, #15.

Now there is two new "packages":
- biblatex-morenames, which adds new `bookineditor` for a `@bookinbook` entry (and also other field)
- biblatex-bookinother, successor of biblatex-bookarticle, which adds new entry type, and also `bookineditor` field (and `bookeditor` field).

Could you try theme.

Here the two packages:
[biblatex-bookinother.zip](https://github.com/maieul/biblatex-bookinarticle/files/160494/biblatex-bookinother.zip)
[biblatex-morenames.zip](https://github.com/maieul/biblatex-bookinarticle/files/160495/biblatex-morenames.zip)

What I mean by "testing":
- Reading the handbook and tell me if not clear.
- Testing the feature with your own need as asked on #5, #11, #12, #13, #14, #15 and by email.
- Make feedback. If there are problems, please do one bullet by problem.

**Comment by doc75** [comment]
@maieul : I guess you meant @doc73 instead of me ;-)

**Comment by Doc73** [comment]
:+1:

**Comment by maieul** [comment]
@doc75 you are right ;-)

**Comment by maieul** [comment]
dear @Doc73  and   @ClintEastwood, do have any idea about when you will have time for test.

**Comment by Doc73** [comment]
Dear Maïeul, I'm at school for a teacher's meeting, but in this days I was
ill.

Il 12:28 mar 08/mar/2016 Maïeul Rouquette <notifications@github.com> ha
scritto:

> dear @Doc73 <https://github.com/Doc73> and @ClintEastwood
> <https://github.com/ClintEastwood>, do have any idea about when you will
> have time for test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maieul/biblatex-bookinarticle/issues/16#issuecomment-193737714>
> .
>
-- 


*Prof. Domenico Cufalo*Via Contessa Matilde 14
56123 Pisa (PI) - Italy
Home: +390509662639
Mobile: +393475207746
E-Mail: cufalo@gmail.com
WebSite: http://tinyurl.com/ndpoq87

**Comment by Doc73** [comment]
Ah, first question!
I see that the new packages is not loaded by `usepackage`, but as `bibstyle`, and that automatically loads `verbose` bibstyle, which I dislike.

Is it possible to use `authortitle` bibstyle instead? If yes, how?

**Comment by maieul** [comment]
You must be the distinction, explained in biblatex handbook, and used in this handbook between:
- the citation style : citestyle
- the bibliographic style : bibstyle

In any case, you are free to use any citation style. And as verbose bibliographic style is equal to authortitle bibliographic style, you can just do 

````
  \usepackage[citestyle=authortitle,bibstyle=morenames]{biblatex}
````

I hope the change on https://github.com/maieul/biblatex-bookinarticle/compare/2.0.0-beta1...2.0.0 will clarify it.

**Comment by Doc73** [comment]
Yes!
I already distinguish between `citestyle` and `bibstyle`, but my question was related to `bibstyle`, not to `citestyle` (for package `biblatex-bookinother`).

Anyway, I see that verbose bibstyle is equal to authortitle bibstyle, so my problem is solved.

However, the problem in general still remains: if someone prefers a different bibstyle (different from verbose), is it possible to use it?

**Comment by maieul** [comment]
yes, using biblatex-multiple-dm

**Comment by maieul** [comment]
but people should use style based, finaly, on the standard.bbx bibstyle, if they want to have coherence in bibliographic style (or they should modify the style for the new entry type)

**Comment by Doc73** [comment]
Ok!
I understood that I have to understand better this `biblatex-multiple-dm`! :smile:

**Comment by Doc73** [comment]
R. 86 supra: "you own", instead of "your own"

**Comment by maieul** [comment]
biblatex-multiple-dm allow you to load multiple datamodel (.dbx) and so bibliographic style (.bbx). I have provided an example here
https://github.com/maieul/biblatex-bookinarticle/compare/2.0.0-beta1...2.0.0#diff-480f4f8090d3d8b423481cb26835b5e5R95

**Comment by maieul** [comment]
hi, some feedbacks ? I would like to publish quickly.

**Comment by Doc73** [comment]
Wait for this weekend

Il 15:58 ven 11/mar/2016 Maïeul Rouquette <notifications@github.com> ha
scritto:

> hi, some feedbacks ? I would like to publish quickly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maieul/biblatex-bookinarticle/issues/16#issuecomment-195400940>
> .
>
-- 


*Prof. Domenico Cufalo*Via Contessa Matilde 14
56123 Pisa (PI) - Italy
Home: +390509662639
Mobile: +393475207746
E-Mail: cufalo@gmail.com
WebSite: http://tinyurl.com/ndpoq87

**Comment by maieul** [comment]
and so ?

**Comment by ClintEastwood** [comment]
Sorry Maieul, that I kept you waiting. I will test it in the coming days. Thanks for your work. I'll get back to you.

**Comment by maieul** [comment]
@ClintEastwood and @Doc73 when do you think to have time to test ?

**Comment by ClintEastwood** [comment]
I am testing today. Looks good so far. I have a new suggestion already, which I shall add as an issue, alright?

**Comment by maieul** [comment]
yes, open new issue



Le 22 mars 2016 � 08:18, ClintEastwood <notifications@github.com> a �crit :

**Comment by ClintEastwood** [comment]
Maieul, good Work. I tested:

- bookinarticle
- bookincollection
- bookinincollection
- bookinproceedings
- bookininproceedings
- bookinthesis

The only error I found was that `bookineditor` does not seem to work for `bookinthesis`.

Question: I assume, you are going to add `bookintranslator`,  `bookinannotator`,  `bookinintroduction`,  `bookincommentator`, etc. as well? On the basis of  `bookineditor` this should be easy, I assume. Good work!

I'll continue testing. If I find something, I'll get back to you.

**Comment by maieul** [comment]
> bookineditor does not seem to work for bookinthesis.

yes, because I assume the editor of the book in a thesis is the author of the thesis ;-)

> Question: I assume, you are going to add bookintranslator, bookinannotator, bookinintroduction, bookincommentator, etc. as well? On the basis ofbookineditor this should be easy, I assume.

Not so easy as that. We have to think to the position where we could add it in the bibliographic notice, we have a lot of entry point. I have not found, for now, a way to automatically add these fields on the good point.

To avoir error, I prefer to add them when people ask for them with a real example, to be sure.

**Comment by ClintEastwood** [comment]
> About the bookineditor for bookinthesis:
Consider the following: Person A *edited* a WORK as part of his/her PhD thesis, while Person B *translated* a WORK as part of his/her PhD thesis.
The Output "Aristotle. Metaphysics. In: Person A. PhD-Thesis. Univesrity of Paris. 2016." Does not give you any information about what you find in that publication. Is it an edition or a translation or both?

This means two things: 
1. Even though you are right that any information regarding a "bookinthesis" deals with the same person being responsible -- it does not precisely give information *in what respect* the person is responsible: is he the editor or the translator? Thus, I think it would be good to add the very same mechanism which governs the "bookineditor" in "bookinarticle" also to "bookinthesis".
2. It would really be good if you could add the same mechanisms for "translator", "annotator", "commentator, "introduction", etc. Biblatex has all these fields and works with them very nicely (it creates phrases like "Edited and annotated, with an introduction, by ..."). Maybe you can draw on this? This brings me to the second point:

> About my question
If you are uncertain about "the position where we could add it in the bibliographic notice", then I would suggest to add it right there where you added the information about the "bookineditor" and that you use the same mechanism which biblatex uses for creating phrases like "Edited and annotated, with an introduction, by ...". There are `bibstrings` like `\bibstring{byeditoranin}`  .What do you think?

**Comment by maieul** [comment]
> 
> 
> This means two things: 
> 1. Even though you are right that any information regarding a "bookinthesis" deals with the same person being responsible -- it does not precisely give information in what respect the person is responsible: is he the editor or the translator? Thus, I think it would be good to add the very same mechanism which governs the "bookineditor" in "bookinarticle" also to "bookinthesis".
You are right. I will try to do it tomorrow, but I can't be sure

> 2. It would really be good if you could add the same mechanisms for "translator", "annotator", "commentator, "introduction", etc. Biblatex has all these fields and works with them very nicely (it creates phrases like "Edited and annotated, with an introduction, by ..."). Maybe you can draw on this? This brings me to the second point:
> 

Again right, but indeed not. Now, I remember why I did'n add these field:
- editor for a @bookinbook means the editor of the *including* book, not the editor of the included book. Cf the biblatex handbook "The editor(s) of the title, booktitle, or maintitle, depending on the entry type. Use the editortype field to specify the role if it is different from �editor�. See � 2.3.6 for further hints."
- for translator, it seems that is the same point. "The translator(s) of the title or booktitle, depending on the entry type. If the translator is identical to the editor, the standard styles will automatically concatenate these fields in the bibliography.". So a bookineditor could be useful. However using for a @bookinbook saw it is the editor of *included book*. Maybe we could ask to @plk to clarify the handbook
- for annotator, it is the annotator of *included book* ("The author(s) of annotations to the work. If the annotator is identical to the editor and/or translator, the standard styles will automatically concatenate these fields in the bibliography. See also commentator.")
- also for commentator ("The author(s) of a commentary to the work.")
- also for "introduction" ("The author(s) of an introduction to the work.")

So there is not reason to create new field. Maybe only to be sur they are merged with the "bookineditor" field ? Could you look for it and, if need, open an issue? I have to think in which package this should be managed.

**Comment by maieul** [comment]
The beta-3 of the package:
- allows bookineditor for @bookinthesis
- create bookinjournal (#17). 

Cf joined file
[biblatex-bookinother-beta3.zip](https://github.com/maieul/biblatex-bookinarticle/files/185699/biblatex-bookinother-beta3.zip)

Please make feedback.

**Comment by maieul** [comment]
@ClintEastwood any feedback ? I propose to you to publish like it now, and for #18 wait a little time the answer on https://github.com/plk/biblatex/issues/390

**Comment by ClintEastwood** [comment]
Will take it on this week or this weekend. promised! thanks.

**Comment by ClintEastwood** [comment]
Or alternatively: yes do publish it. It has plenty of functionality already. And then I can test more this week and we can see what else needs to be done.

**Comment by maieul** [comment]
I will publish it friday. For now I have no time for release checking�

**Comment by Doc73** [comment]
Dear Maieul, any news?
There is a new version of `biblatex-bookinother`? I was stucked with beta3.

Due to TL2015 freeze, do we have to wait for TL2016?

**Comment by maieul** [comment]
biblatex-bookintoher 2.0.0 is on CTAN. But as texlive 2015 is frozen, you have to wait texlive 2015, or to do a manual installation

**Comment by Doc73** [comment]
Many thanks. Just downloaded!

Il giorno mar 12 apr 2016 alle ore 00:11 Maïeul Rouquette <
notifications@github.com> ha scritto:

> biblatex-bookintoher 2.0.0 is on CTAN. But as texlive 2015 is frozen, you
> have to wait texlive 2015, or to do a manual installation
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/maieul/biblatex-bookinarticle/issues/16#issuecomment-208586040>
>
-- 


*Prof. Domenico Cufalo*Via Contessa Matilde 14
56123 Pisa (PI) - Italy
Home: +390509662639
Mobile: +393475207746
E-Mail: cufalo@gmail.com
WebSite: http://tinyurl.com/ndpoq87
