### ISSUE TITLE
for bookinother: add @bookinjournal

### ISSUE THREAD

**Issue by ClintEastwood** [maieul/biblatex-bookinarticle#17]
You started your fine idea with the package `bookinarticle`. An entry for this would give the following result:
> Author of Work. *Title of Work. Subtitle of Work* Edited by Author of Article. In: Author of Article. "Title of Article. Subtitle of Article". In: *Journal* No. 4 (2016), 16–39.

An example would be:
> Aristotle. *De lineis insecabilibus*. Edited by John Doe. In: Jon Doe. "A brief Work of Aristotle Newly Discussed". In: *Journal* No. 4 (2016), 16–39.

This is perfect **if** the title of the "Title of Work" and the "Title of Article" are *different from each other*.

However, I realised that very often (!) the "author of the article" decided to call his/her article by the name of the Title of the Work of the Author of the Work, so that the "Title of Work" and the "Title of Article" are precisely *not* the same.

For example:
> Jon Doe. "Aristotle. *De lineis insecabilibus*". In: *Journal* No. 4 (2016), 16–39.

In that case your `bookinarticle` would give the following:
> Aristotle. *De lineis insecabilibus*. Edited by John Doe. In: Jon Doe. "Aristotle. *De lineis insecabilibus*". In: *Journal* No. 4 (2016), 16–39.

This I find inadequate, because it simply gives twice the author of the work and the title of the work. Since this happens so often, would you agree that we should also have a `@bookinjournal` which would give the following result:
> Author of Work. *Title of Work. Subtitle of Work* Edited by Author of Article. In: *Journal* No. 4 (2016), 16–39.

An example would be:
> Aristotle. *De lineis insecabilibus*. Edited by John Doe. In: *Journal* No. 4 (2016), 16–39.

**Comment by maieul** [comment]
I see. But what should you not use an @article entry with an ineditor field ? 

@article{
	Author = {Ancien Author},
	Title = {Ancient Work},
	Ineditor = {Modern Editor},
	Etc
}
?

**Comment by ClintEastwood** [comment]
Because it prints the "title if the ancient work" in quotation marks and not in italics. Consider "bookincollection". This is basically the same as "incollection" but pints the title in italics. 

This is precisely why your "bookinother" package is so valuable.

**Comment by maieul** [comment]
you are right. Please provides a .bib  MWE.
Should be quite easy to implement. It a just an alias of @article with some specific formating rules

**Comment by ClintEastwood** [comment]
Thanks. Will do later. I owe you!

**Comment by ClintEastwood** [comment]
Here is the MWE. Thanks.

    %!TEX TS-program = lualatexmk
    \documentclass{scrartcl}
    \usepackage{fontspec}
    \usepackage[backend=biber,style=authortitle-comp,abbreviate=false]{biblatex}
    \usepackage{biblatex-bookinarticle}
    \usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @bookinjournal{alexander:sharples:1982,
    Author = {{Alexander of Aphrodisias}},
    Title = {On Time},
    Journaltitle = {Phronesis},
    Number = {1},
    Pages = {58--81},
    Bookineditor = {Robert W. Sharples},
    %Bookinannotator = {Robert W. Sharples},
    %Bookinintroduction = {Robert W. Sharples},
    %Bookintranslator = {Robert W. Sharples},
    Volume = {27},
    Year = {1982}}
    \end{filecontents}
    \addbibresource{\jobname.bib}
    \begin{document}
    This is the ancient text published in translation/edition in a journal: \cite{alexander:sharples:1982}.
    \printbibliography
    \end{document}

**Comment by maieul** [comment]
for the other field,  I wait for your test mentionned in the issue #16
