### ISSUE TITLE
[Feature Request] Bookininbook

### ISSUE THREAD

**Issue by Doc73** [maieul/biblatex-bookinarticle#23]
Hi Maieul!

For example [https://archive.org/details/scholiaintheocri00buss](https://archive.org/details/scholiaintheocri00buss), where _Scholia in Theocritum_ are published by Duebner, _Scholia in Nicandrum et Oppianum_ by Bussemaker.

Many thanks in advance,
Domenico

**Comment by maieul** [comment]
yes, I have the same need for my phd. 

let me wait I finish the main content (normally, in August / September)

**Comment by Doc73** [comment]
:+1: 

In Italy, in these circumstances we say "In bocca al lupo", which means "Good luck"! :smile:

**Comment by maieul** [comment]
I will do it tomorrow, and I hope also for #20.

**Comment by Doc73** [comment]
Thank you very much in advance!

**Comment by maieul** [comment]
hum. in your case, should you use @bookinincollection instead of @bookininbook ? 
Reading the biblatex handbook, I understand that @incollection are for entry with distinct author, that is your cas, while @inbook are for entry with the same author as @book (that is my case, as I use a book with collected article)

**Comment by maieul** [comment]
please make feedback on branch "issue23".  I will look for issue #20 this afternoon.

**Comment by Doc73** [comment]
My case is really strange: there is a book, which contains two other books, by two author, where two different ancient texts are published.

The schema is the following:
```tex
@Collection{Duebner1878,
  author    = {Dübner, F. and Bussemaker, U. Cats},
  booktitle = {Scholia in Theocritum, Nicandrum et Oppianum},
  location  = {Parisiis},
  publisher = {Editore Ambrosio Firmin--Didot},
  year      = {1878},
}

@Incollection{Bussemaker1878,
  author     = {Bussemaker, U. Cats},
  title      = {Scholia et Paraphrases in Nicandrum et Oppianum},
  year       = {1878},
  pages      = {243--364},
  crossref   = {Duebner1878},
  titleaddon = {Partim nunc primum edidit, partim collatis cod. mss. emendavit, annotatione critica instruxit et indices confecit},
}

@Bookinincollection{ScholiainOppianum1878,
  author    = {{Scholia~in~Oppianum}},
  title     = {In Halieutica},
  pages     = {260--364},
  year      = {1878},
  crossref  = {Bussemaker1878},
}

@Bookinincollection{ScholiainOppianum1878a,
  author    = {{Scholia~in~Oppianum}},
  title     = {In Cynegetica},
  pages     = {243--259},
  year      = {1878},
  keywords  = {auctores},
  crossref  = {Bussemaker1878},
}
```
If you tries this code, you'll have an "error" in `titleaddon` which would have been related to the title of the `incollection`.

P.S.: branch #20 is fine

**Comment by maieul** [comment]
ok, I will look tomorrow.

**Comment by Doc73** [comment]
This is the result:

> Scholia in Oppianum. _In Cynegetica_ . Partim nunc primum edidit, partim collatis cod. mss. emendavit, annotatione critica instruxit et indices confecit. In: U. C. Bussemaker. “Scholia et Paraphrases in Nicandrum et Oppianum”. In: _Scholia in Theocritum, Nicandrum et Oppianum_. Parisiis, 1878, pp. 243–259.

But I would expect:

> Scholia in Oppianum. _In Cynegetica_. In: U. C. Bussemaker. “Scholia et Paraphrases in Nicandrum et Oppianum”. Partim nunc primum edidit, partim collatis cod. mss. emendavit, annotatione critica instruxit et indices confecit. In: F. Dübner and U. C. Bussemaker, _Scholia in Theocritum, Nicandrum et Oppianum_. Parisiis, 1878, pp. 243–259.

**Comment by maieul** [comment]
I am looking on it.

Ps : notes that you don't need to recopy the "year" field: it is inherited. I suggest you, also, to use date field instead, with new format for date range (BEGIN/END)

**Comment by maieul** [comment]
1. Please try branch issue23. The new version solves the inheritance of titleaddon.
2. Please look on the change mode on your example in 44deb3e

**Comment by Doc73** [comment]
No, @issue23 don't give the expected result:
> Scholia in Oppianum. _In Cynegetica_. In: U. C. Bussemaker. _Scholia et Paraphrases in Nicandrum et Oppianum_. Partim nunc primum edidit, partim collatis cod. mss. emendavit, annotatione critica instruxit et indices confecit. In: **F. Dübner and U. C. Bussemaker**, _Scholia in Theocritum, Nicandrum et Oppianum_. Parisiis, 1878, pp. 243–259.

Please, note the names of Dübner and Bussemaker, i. e. the editor of the two "books" joined together in a single volume whose title is _Scholia in Theocritum, Nicandrum et Oppianum_.

As for the repetition of year, it depends on the fact that I want Jabref automatically generates a key in the form AuthorYear.

**Comment by maieul** [comment]
you didn't ask for this problem� so that is normal I didn't solve it.

**Comment by Doc73** [comment]
Sorry, but in my previous post I pointed out to this issue, albeit perhaps too cursory.

**Comment by maieul** [comment]
Ok, I see. But as the model are complex and long, please ask **explicitly** for field problematic ;-). You have asked for titleaddon, so I have corrected it.

So, the new version of the branch should:
- solve the problem of mainauthor 
- solve the problem of title in double

**Comment by Doc73** [comment]
Ok! I understand! :+1:

**Comment by maieul** [comment]
@Doc73 if you could look before midnight, it will allow me to publish it today, and so not to change the date in all the file (an operation with a lot of error)

**Comment by Doc73** [comment]
Ok! It's ready?

**Comment by maieul** [comment]
yes, cf the hand of my message ;-)

**Comment by maieul** [comment]
`So, the new version of the branch should:
- solve the problem of mainauthor
- solve the problem of title in double`

**Comment by Doc73** [comment]
Yes, it works very well! ;-)
Now, I go to sleep: tomorrow I'll wake up at 0600!
