### ISSUE TITLE
unwanted phrase "volume" in 'bookinjournal'

### ISSUE THREAD

**Issue by ClintEastwood** [maieul/biblatex-bookinarticle#28]
there is an unwanted phrase 'volume' before the "volume.number" of the journal in the bookinjournal type.

Example:
Author, Name. Title Name: Yeah. In: Journaltitle **volume** 27.3 (2017), 39–60.

Can you please remove the "volume" phrase here?

**Comment by maieul** [comment]
Unfortunatly, my computer is out of service, and I can't solve your 
problem now. But in any case please add a MWE

**Comment by ClintEastwood** [comment]
It's easy, you will immediately see the problem.

```
% !TEX TS-program = lualatexmk
\documentclass{scrbook}
\usepackage[tools=bookinother,bibstyle=authortitle-comp]{biblatex-multiple-dm}
\usepackage[backend=biber,bibstyle=multiple-dm,citestyle=authortitle-comp,abbreviate=false]{biblatex}
\begin{filecontents}{\jobname.bib}
@bookinjournal{alexander:sharples:1982,
	Author = {{Alexander of Aphrodisias}},
	Journaltitle = {Phronesis},
	Number = {1},
	Pages = {58--81},
	Rating = {4},
	Read = {1},
	Title = {On Time},
	Titleaddon = {\bibstring{bytranslator} Robert W. Sharples},
	Volume = {27},
	Year = {1982}}
\end{filecontents}
\addbibresource{\jobname.bib}
\usepackage{biblatex-bookinarticle}
\begin{document}
\fullcite{alexander:sharples:1982}
\end{document}
```

I'd be happy if you could fix that quickly. many thanks for your work!

**Comment by maieul** [comment]
It is easy, but I have no time to prepare MWE. I can fix problem only
If i Have it, because looking for the origin of a problem take time,
and I have no time to produce MWE to look for the origin.Le samedi 18 novembre 2017 à 17:14 +0000, ClintEastwood a écrit :

**Comment by maieul** [comment]
Please try the branch issue28

**Comment by ClintEastwood** [comment]
Well I did prepare an MWE for you didn’t I?

**Comment by ClintEastwood** [comment]
perfect. works like a charm! thanks!

**Comment by maieul** [comment]
Yes, you prepared a MWE, but not while opening issue, only when I asked you. Anyway, I will publish this branch today.
