### ISSUE TITLE
shortauthor field in bookinarticle entry

### ISSUE THREAD

**Issue by sonator** [maieul/biblatex-bookinarticle#3]
Is it possible to activate the shortauthor field of a bookinarticle entry, too; so as the shorttitle field of the MWE is working? At the moment shortauthor will be ignored.

@bookinarticle{LodovicoPirano,
 keywords	= {quelle},
 hyphenation	= {latin},
 author		= {{Lodovico da Pirano}},
 shortauthor	= {{Lod\adddotspace da Pirano}},
 title			= {Regulae memoriae artificialis},
 shorttitle		= {Regulae mem\adddotspace artif\adddot},
 bookauthor	= {Baccio Ziliotto},
 maintitle		= {Frate Lodovico da Pirano e le sue Regulae memoriae artificialis},
 journaltitle	= {Atti e memorie della Società Istriana di archeologia e storia patria},
 volume		= {49},
 year		= {1937},
 pages		= {189--224}
}

**Comment by maieul** [comment]
the package use the standard bibmacro 
author/translator+others

this bibmacro refers to the bibmacro author. You should modify it. 

the problem is the same with other entry times. It's link with the default behavior of biblatex=

**Comment by sonator** [comment]
Thank you for the rapid answer and hint!  

	I will chance it. 

	-----Original-Nachricht----- 

	Betreff: Re: [biblatex-bookinarticle] shortauthor field in
bookinarticle entry (#3) 

	Datum: Tue, 03 Feb 2015 11:32:29 +0100 

	Von: Maïeul Rouquette <notifications@github.com> 

	An: maieul/biblatex-bookinarticle
<biblatex-bookinarticle@noreply.github.com> 

 the package use the standard bibmacro 
 author/translator+others 

 this bibmacro refers to the bibmacro author. You should modify it. 

 the problem is the same with other entry times. It's link with the
default behavior of biblatex= 

	—
Reply to this email directly or view it on GitHub [1].   

 Profitieren Sie von der sicheren E-Mail-Übertragung Ihrer Daten mit
einer kostenlosen E-Mail-Adresse der Telekom.
www.t-online.de/email-kostenlos

Links:
------
[1]
https://github.com/maieul/biblatex-bookinarticle/issues/3#issuecomment-72628223

**Comment by sonator** [comment]
Addendum: 
Sorry, my question was, as I assume, unclearly expressed. The shortauthor field is ignored, when I cite the entry in a footnote. Of course, the bibliography itself is okay!

**Comment by maieul** [comment]
yes, but this problem is not linked with bookinarticle. try for example with 

`````
@book{LodovicoPirano,
keywords = {quelle},
hyphenation = {latin},
author = {{Lodovico da Pirano}},
shortauthor = {{Lod\adddotspace da Pirano}},
title = {Regulae memoriae artificialis},
shorttitle = {Regulae mem\adddotspace artif\adddot},
bookauthor = {Baccio Ziliotto},
maintitle = {Frate Lodovico da Pirano e le sue Regulae memoriae artificialis},
journaltitle = {Atti e memorie della Società Istriana di archeologia e storia patria},
volume = {49},
year = {1937},
pages = {189--224}
}
`````

You should redefine the author macro (define in biblatex.def)

For example like this :
`````
\renewbibmacro*{author}{%
  \ifboolexpr{
    test \ifuseauthor
    and
    not test {\ifnameundef{author}}
  }
    {\ifnameundef{shortauthor}{\printnames{author}}{\printnames{shortauthor}}%
     \iffieldundef{authortype}
       {}
       {\setunit{\addcomma\space}%
        \usebibmacro{authorstrg}}}
    {}}
`````

**Comment by sonator** [comment]
Thank you very much! At the moment I am in a rush. I will give a feedback this evening.

**Comment by sonator** [comment]
The use of shortauthor in a 'normal' book entry of biblatex did not cause any problem. 

My concern is: When I cite a bookinarticle entry
- the shortauthor should appear in the footnote 
- the 'long' author should appear in the bibliography

When I use your renewed bibmacro*{author}, it occurs vice versa: 
- the shortauthor is appearing in the bibliography 
- the 'long version' of author is appearing in the footnote

**Comment by maieul** [comment]
I am sorry, but I don't understand when you said "a 'normal' book entry of biblatex did not cause any problem", what do you mean :
- the default behavior (don't use of short name) is what you need
- the default behavior (use of short name) is what you need.

I will answer tomorrow, but as I said, the problem is not specific to bookinarticle

**Comment by sonator** [comment]
Good morning!
Please excuse my insisting on a pseudo-problem! 

In my MWE 
- the genuine biblatex entry 'bookinbook' (JacobRagona) produces, if cited, the short form of the author name in a note and the long form in the bibliography. That is the default behaviour. 
- the entry 'bookinarticle' (LodovicoPirano) produces the long form of the author name in a note and in the bibliography as well. In the note, I think, should appear the short form. 

Is that a problem of biblatex?

\begin{filecontents}{\jobname-bib.bib}
@bookinbook{JacobRagona,
 keywords			= {quelle},
 hyphenation	= {latin},
 author				= {Jacobus Ragona},
 shortauthor	= {{Jac\adddotspace Ragona}},
 title				= {Ars memorie artificialis [Vicenza 1434]},
 shorttitle		= {Ars mem\adddotspace artif\adddot},
 bookauthor		= {Zappacosta, Guiglielmo},
 maintitle		= {Studi e ricerche sull'umanesimo italiano},
 series				= {Saggi e ricerche di lingua e letteratura italiana},
 number				= {5},
 location			= {Bergamo},
 year					= {1972},
 pages				= {7--61}
}

@bookinarticle{LodovicoPirano,
 keywords			= {quelle},
 hyphenation	= {latin},
 author				= {{Lodovico da Pirano}},
 shortauthor	= {{Lod\adddotspace da Pirano}},
 title				= {Regulae memoriae artificialis},
 shorttitle		= {Regulae mem\adddotspace artif\adddot},
 bookauthor		= {Baccio Ziliotto},
 maintitle		= {Frate Lodovico da Pirano e le sue Regulae memoriae artificialis},
 journaltitle	= {Atti e memorie della Società Istriana di archeologia e storia patria},
 volume				= {49},
 year					= {1937},
 pages				= {189--224}
}
\end{filecontents}

\documentclass{book}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage[babel]{csquotes}
\usepackage[style=authortitle,backend=biber]{biblatex}
\usepackage{biblatex-bookinarticle}

\begin{document}
\footnote{\cite[Confer][]{JacobRagona} S.\,123.}
\footnote{\cite[Confer][]{LodovicoPirano} S.\,456.}
\printbibliography
\end{document}

**Comment by maieul** [comment]
ok, you should have said that you don't use the verbose style, which is the model of biblatx-bookinarticle (� 8 of the handbook).

I will send you an solution.

In any case, you have a bad use of \cite command, to print the page number.

You should use 

\footcite[Confer][123]{JacobRagona}
\footcite[Confer][456]{LodovicoPirano}

instead of 

\footnote{\cite[Confer][]{JacobRagona} S.\,123.}
\footnote{\cite[Confer][]{LodovicoPirano} S.\,456.}

(read the handbook of biblatex about optional argument + \footcite command

**Comment by maieul** [comment]
so, now, with a real MWE, I can understand what is your need and what is the problem.

You should try the branch "issue3". You should put the .sty file along your .tex file and then :
- run xelatex/pdflatex
- run biber
- run xelatex/pdflatex

**Comment by sonator** [comment]
Uff! Now, I get the results I wished to have with style=authortitle. 

You are right, some of my uses are amateurish. And please be sure, that I'm much obliged for your assistance. For historians the bookinarticle entry is highly useful, because a lot of sources are edited as appendices in articles. 

The former version of bookinarticle was compatible with style=authortitle-dw. Is it difficult to reconcile the new version with authortitle-dw, too? This style is very helpful for german users. When that costs too much time, please set the question aside!

In any case, thank you!

**Comment by maieul** [comment]
this version has not broken compatibility with authortitle-dw. Or if it is the case, please send a MWE...

**Comment by sonator** [comment]
You are right, my tests were successful. 
So, in one word: Merci!

**Comment by maieul** [comment]
you're welcome. But please next time send a full MWE. I have published in CTAN
