### ISSUE TITLE
Year not printed ?

### ISSUE THREAD

**Issue by maieul** [maieul/biblatex-bookinarticle#6]
from @doc73
"year" field of bookinarticle is not prited.
I load biblatex in this way:

\usepackage[%
  	style=philosophy-classic,%
   backend=biber,%
   dashed=true,%
   url = false,%
  	isbn = false,%
  	firstinits=true,%
  	uniquename=init%
]{biblatex}
\usepackage{biblatex-bookinarticle}

Here is a sample of bibtex entry:

@Bookinarticle{Boethus1985, 
    author = {Boethus}, 
    bookauthor = {Dyck, Andrew R.}, 
    journal = {«Harvard Studies in Classical Philology»}, 
    pages = {75--84}, 
    title = {Lexicorum platonicorum fragmenta}, 
    volume = {89}, 
    year = {1985}, 
    keywords = {auctores}, 
    maintitle = {Notes on platonic lexicography in antiquity}, 
    shorthand = {Boeth.}
 }

**Comment by Doc73** [comment]
I'm preparing a MWE.

**Comment by maieul** [comment]
ok.

that is not related, but  you should not add the quotation mark in the "journal" field but let biblatex add it for you.

**Comment by maieul** [comment]
in the MWE I provided in branch issue6 I saw no problem.

**Comment by Doc73** [comment]
Yes, I've already corrected Journal field. The quotation marks were inherited from previous bib type.

**Comment by Doc73** [comment]
```tex
% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\begin{filecontents}{biblio.bib}
@Bookinarticle{Boethus1985,
  author =     {Boethus},
  bookauthor = {Dyck, Andrew R.},
  journal =    {Harvard Studies in Classical Philology},
  pages =      {75--84},
  title =      {Lexicorum platonicorum fragmenta},
  volume =     {89},
  year =       {1985},
  keywords =   {auctores},
  maintitle =  {Notes on Platonic lexicography in antiquity},
  shorthand =  {Boeth.}
}
\end{filecontents}

\documentclass[11pt,a4paper]{book}
\usepackage{fontspec}
    \setmainfont{Linux Libertine O}

\usepackage{polyglossia}
    \setmainlanguage[babelshorthands=true]{italian}

\usepackage[%
	style=philosophy-classic,%
	backend=biber,%
	dashed=true,%
	url = false,%
	isbn = false,%
	firstinits=true,%
	uniquename=init,%
	]{biblatex}
\usepackage{biblatex-bookinarticle}
\bibliography{biblio}

\begin{document}
\nocite{*}
\printbibliography

\newpage
\nocite{*}
\printbiblist[%
	keyword=auctores,%
	title={Auctores in apparatu frequentius laudati}%
	]{shorthand}
\end{document}
```

Please, see chapter _Auctores..._. Also, is not very beautiful the result

> Boethus (1985)

IMO, there are incompatibilities with ```biblatex-philosophy``` style.

**Comment by maieul** [comment]
I have tried to compare the result of @article and @bookinarticle with philosophy-classic style. All are similar.
So I don't understand the problem. Cf my own MWE on branch issue6

**Comment by Doc73** [comment]
Yes, as I write above, the year appears in ```\printbibliography```, although in an inelegant way.

However, there is not year at all in ```\printbiblist{shorthand}```.

**Comment by maieul** [comment]
The inelegant way is the standard way of philosophy-classic. So change your style or customize it, but the principe of biblatex-bookinarticle is to be as close as possible to your style.

The absence of date in the shorthand list is the same problem.

So : customize philosophy-classic style.

**Comment by Doc73** [comment]
Ok, many thanks!
A simple way I found is add year in `volume` field. Ex. gr. ```volume = {65 (1885)}```

**Comment by maieul** [comment]
It is not a good way. You should modify your style.

**Comment by Doc73** [comment]
Which style do you recommend?

**Comment by maieul** [comment]
personnaly, I use the default style of biblatex (verbose-trad2). But you should learn how to customize your style.

- You can read the chapter devoted to this topic in my book http://geekographie.maieul.net/95
- You can ask for your problem, which (as the article example shows) is not related to bookinarticle, to https://tex.stackexchange.com/. Take as MWE this 

````

@article{Dyck1985,		
-  author = {Dyck, Andrew R.},		
-  journal =    {Harvard Studies in Classical Philology},		
-  pages =      {55-99},		
-   keywords = {auctores}, 		
-   shorthand = {Dyck.},		
-  volume =     {89},		
-  year =       {1985},		
-  title =  {Notes on Platonic lexicography in antiquity},		
-}
`````

**Comment by Doc73** [comment]
Beh, this is not easy. As you can see from my MWE, the issue is related to ```biblist```. I will think about what to do.

Meanwhile, thank you so much yet! :-)

**Comment by maieul** [comment]
write a MWE not related to bookinarticle and send a message on SE. Many 
people could answer to you

**Comment by Doc73** [comment]
Ok! I asked in the forum where the author of `biblatex-phisosophy` is active.

Cf. [http://www.guitex.org/home/it/forum/5-tex-e-latex/105009-biblatex-philosophy-biblist-non-stampa-la-data-di-articoli#105009](url)

I think is a bug!
