### ISSUE TITLE
add: bookinphdthesis

### ISSUE THREAD

**Issue by ClintEastwood** [maieul/biblatex-bookinarticle#8]
Dear Maïeul,
Once more our paths are crossing... I am very happy that you coded this package here. WOUld you mind adding also a `bookinphdthesis` type?
Phd-theses were (and still are!) not always published but still may contain editions/translations of ancient texts. There is currently no way to treat editions/translations published in or as PhD-theses adequately.
Thanks and keep up the good work!
ClintEastwood

**Comment by maieul** [comment]
oh, you are right !

please provides me a MWE contening the entry @phdthesis and the subentry @bookinphdthesis with the field. 

It should be easy to add it in the .sty file.

**Comment by ClintEastwood** [comment]
Sure. Thanks so much!

    %!TEX TS-program = lualatexmk
    \documentclass{scrbook}
    \usepackage{fontspec}
    \usepackage[backend=biber,style=authortitle-comp,abbreviate=false]{biblatex}
    \usepackage{biblatex-bookinarticle}
    \usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @phdthesis{phd:2015,
    	Address = {Paris},
    	Author = {John Doe},
    	Title = {A Nice Title},
    	Subtitle = {A Very Nice Subtitle},
    	School = {Sorbonne},
    	Year = {2015}}
    @bookinphd{inphd:2015,
    	Author = {Aristotle},
    	Title = {The Ancient Text},
    	Titleaddon = {\bibstring{byeditortranin} John Doe}}
    	Crossref = {phd:2015},
    	Pages = {20--55},
    \end{filecontents}
    \addbibresource{\jobname.bib}
    \begin{document}
    This is the PhD: \cite{phd:2015} and this is the text published in a PhD: \cite{inphd:2015}.
    \printbibliography
    \end{document}

**Comment by maieul** [comment]
ok.

I have not implemented directly @bookinphdthesis but @bookinthesis with fied type=thesis, as biblatex standard way: @phdthesis is just @thesis with fied type=thesis.

please try the branch issue8. please also look on the new handbook available on https://drive.switch.ch/public.php?service=files&t=cd0d0a81f4956f246b5a2f7020beec22

**Comment by ClintEastwood** [comment]
nice. it seems to work. I'll test more in the coming days. So far I did not recognise any misbehaviour. Thanks!

**Comment by maieul** [comment]
ok. please tell me when I could publish.

**Comment by ClintEastwood** [comment]
I think you can. So far no errors. Thanks!

**Comment by maieul** [comment]
I do it. Thanks for your tests.

**Comment by maieul** [comment]
@ClintEastwood The version 1.3.0, for this need, added a big bug (with the field "journal" of a @article). Version 1.3.1, send on CTAN, fix it in emergency.

**Comment by ClintEastwood** [comment]
@maieul : thanks for letting me know.
