### ISSUE TITLE
Ancient Work in a series

### ISSUE THREAD

**Issue by Doc73** [maieul/biblatex-bookinarticle#9]
Dear Maieul,
I'm sorry to bother you always!

I'm searching a way to cite ancient texts published in series as Grammatici Graeci, Commentaria in Aristotelem Graeca etc. etc.
These are series published in many years by lots of editors.
Until now, I used the `bookinbook` entry, but the results aren't optimal.

An example:
- Ancient text: Apollonius Dyscolus, De Pronominibus
- Modern editor: Richard Schneider
- Published in: Grammatici Graeci Pars II, vol. I.1
All the works of ApDysc are published in Grammatici Graeci II, but its volume I.1 is by Schneider, while the volume I.2 is by Uhlig (I think because the former was died).

Grammatici Graeci Pars I is devoted to Dionysius Thrax; pars III to Herodianus. All these volumes are by different editors...

As you see, the situation is very complex and I can not find a standard method for proper indexing.

Your `bookinincollection` doesn't fit this sort of cases, if I understand correctly.

Do you think is possible to integrate complex cases like this in your precious package?
I would be really grateful if you could find a way. However, I have no urgency. Take the time you need! :smiley:

**Comment by maieul** [comment]
I am not sur to understand well you problem. For my part as use thing like this :
- @bookinbook  as type
- booktitle as the title of the volume including my text
- `series` field is the series. So in your case `Grammatici Graeci`
- number : number in the series. In your case Pars II
- editor as the editor of current book
- maintitle as the title of subseries, devoted for one old author
- volume as the volume in the subseries.


@book{CCSL72,
	Date-Added = {2015-04-30 16:08:27 +0000},
	Date-Modified = {2015-04-30 16:12:38 +0000},
	Maintitle = {S. Hieronymi Presbyteri Opera},
	Number = {72},
	Series = {Corpus Christianorum Series Latina},
	Title = {Hebraicae quaestiones in libro Geneseos. Liber interpretationis hebraicorum nominum. Commentarioli in psalmos. Commentarius in Ecclesiasten},
	Volume = {Pars~I Opera Exegetica~1}}

@bookinbook{CPL581,
	Annote = {voir dans la LLTA },
	Author = {J�r�me},
	Cpl = {581},
	Crossref = {CCSL72},
	Date-Added = {2015-04-30 16:15:51 +0000},
	Date-Modified = {2015-04-30 16:19:17 +0000},
	Editor = {Paul de Lagarde},
	Pages = {57-161},
	Title = {Liber interpretationis hebraicorum nominum}}

So I don't see in which way this package is concerned. It is mainly concerned for book edited not in book !

**Comment by Doc73** [comment]
Ah, ok! Your way is almos mine:

```tex
@Bookinbook{ApDyscPron,
  author =         {{Apollonius Dyscolus}},
  title =          {De Pronominibus},
  editor =         {Schneider, R.},
  shorthand =      {Ap.Dysc. \textit{Pron.}},
  keywords =       {auctores},
  pages =          {1--116},
  crossref =       {ApDysc},
}

@Book{ApDysc,
  maintitle =      {Apollonii Dyscoli Quae supersunt},
  %maintitleaddon = {recensuerunt, apparatum criticum, commentarium, indices adiecerunt},
  editor =         {Schneider, R. and Uhlig, G.},
  series =         {Grammatici Graeci},
  number =         {Pars~II},
  maintitle =      {Appollonii scripta minora a Richardo Schneidero edita continens},
  year =           {1878},
  volume =         {I},
  part =           {1},
  location =       {Lipsiae},
  publisher =      {In aedibus B. G. Teubneri},
}
```
You could close this bug report. :+1:
